// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Account struct {
	ID             uuid.UUID
	Owner          string
	Balance        decimal.Decimal
	Currency       string
	CreatedAt      time.Time
	LastModifiedAt time.Time
}

type Entry struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	Amount    decimal.Decimal
	CreatedAt time.Time
}

type Transfer struct {
	ID            uuid.UUID
	FromAccountID uuid.UUID
	ToAccountID   uuid.UUID
	Amount        decimal.Decimal
	CreatedAt     time.Time
}
